version: 2
updates:
- package-ecosystem: npm
  directory: "/packages/pigly"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  versioning-strategy: widen
  ignore:
  - dependency-name: highlight.js
    versions:
    - 10.5.0
    - 10.6.0
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: yargs-parser
    versions:
    - 13.1.2
  - dependency-name: y18n
    versions:
    - 4.0.0
  - dependency-name: ts-auto-mock
    versions:
    - 3.0.0
    - 3.1.0
    - 3.1.1
  - dependency-name: "@types/node"
    versions:
    - 14.14.17
    - 14.14.22
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
  - dependency-name: "@types/mocha"
    versions:
    - 8.2.0
